ckpt: last
resume_dir: outputs/mmr_1013_1

run_dir: outputs/${hydra:runtime.choices.model}_${hydra:runtime.choices.data}_${hydra:runtime.choices.data/motion_loader}

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  num_workers: 8

defaults:
  - data: humanml3d
  - model: mmr
  - trainer
  - defaults
  - _self_
